from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import StudentModelViewSet, StudentViewSet, StudentReadOnlyViewSet

# router and register the StudentModelViewSet with it
router = DefaultRouter()
router.register(r'students', StudentModelViewSet, basename='student')

# router for the StudentReadOnlyViewSet and register it
readonly_router = DefaultRouter()
readonly_router.register(r'students-read-only', StudentReadOnlyViewSet, basename='student-read-only')

# router for the custom StudentViewSet and register it
custom_router = DefaultRouter()
custom_router.register(r'students-custom', StudentViewSet, basename='student-custom')

# Now, retrieve the URL patterns generated by all routers
urlpatterns = router.urls
urlpatterns += readonly_router.urls
urlpatterns += custom_router.urls
